### ISSUE TITLE
get ISP data too?

### ISSUE THREAD

**Issue by wmantly** [GitSquared/node-geolite2-redist#10]
Is there a way to get the ISP for an IP as well?

**Comment by GitSquared** [comment]
The `GeoLite2-ASN` database bundled in this redist might be what you're looking for. ([What is an ASN](https://en.m.wikipedia.org/wiki/Autonomous_system_(Internet)))

**Comment by wmantly** [comment]
Combined with this, it does. Thank you.

http://www.bgplookingglass.com/list-of-autonomous-system-numbers
