### ISSUE TITLE
Using behind proxy

### ISSUE THREAD

**Issue by rvalle** [GitSquared/node-geolite2-redist#23]
My service is in a closed network  access to Internet via proxy.

I wonder now to enable proxy support. typical environment variables are not working.

Seems like this library is using ```got``` as http agent

And the documentation mentions that it is possible to create a "global-agent"

Any idea how that would go?

**Comment by GitSquared** [comment]
Yes, we don't currently support proxy configs. I could add that in, could you tell me which environment variables you're trying to use so i can get an idea of the config you'd like?

(tech impl notes: got docs recommend using a proxy agent, see [here](https://github.com/sindresorhus/got/blob/main/documentation/tips.md#proxying))

**Comment by rvalle** [comment]
I was attempting to use the standard HTTP_PROXY, HTTPS_PROXY and NO_PROXY

After reviewing the documentation my server needed only:

```
import 'global-agent/bootstrap';
```

That one-liner fixes it all, for this and other HTTP client usages, although environment variables are customizable.

**Comment by GitSquared** [comment]
Interesting, thanks for the ref. Seems like you can indeed override the [global agent](https://nodejs.org/dist/latest-v16.x/docs/api/http.html#httpglobalagent) for all HTTP requests from Node!
