### ISSUE TITLE
Module crashes. Missing Database GeoLite2-Country

### ISSUE THREAD

**Issue by atlanteh** [GitSquared/node-geolite2-redist#24]
Hey, we have a production issue.. seems like since today this file is missing:
https://raw.githubusercontent.com/GitSquared/node-geolite2-redist/master/redist/GeoLite2-Country.tar.gz

Can you please fix?

**Comment by GitSquared** [comment]
@atlanteh just fixed, thanks for pinging me.

Sounds like a very rare bug but I've added an issue #25 to track fixing it for good.

**Comment by atlanteh** [comment]
Thanks for the superfast response!
