### ISSUE TITLE
Databases can be missing if only one of them needs to be updated

### ISSUE THREAD

**Issue by GitSquared** [GitSquared/node-geolite2-redist#25]
First reported in #24 after [this workflow](https://github.com/GitSquared/node-geolite2-redist/runs/6564992899?check_suite_focus=true)

**Comment by caub** [comment]
The latest commit https://github.com/GitSquared/node-geolite2-redist/tree/master/redist contains GeoLite2-City.tar.gz, GeoLite2-Country.tar.gz but not GeoLite2-ASN.tar.gz is this normal?

**Comment by caub** [comment]
can we expect GeoLite2-City.tar.gz to be always in the redist/ directory? (when the issue is fixed)

Thanks for your work btw

**Comment by caub** [comment]
> The latest commit https://github.com/GitSquared/node-geolite2-redist/tree/master/redist contains GeoLite2-City.tar.gz, GeoLite2-Country.tar.gz but not GeoLite2-ASN.tar.gz is this normal?

ASN was missing 1 minute ago

Apparently the CI rewrite the whole git history each time (makes sense since they are large files)

**Comment by GitSquared** [comment]
@caub good catch 🙈, fixed in [this run](https://github.com/GitSquared/node-geolite2-redist/commit/80cdfb6da924bd28b6f443a2a5236a7507442ca9)

I'm looking into fixing the underlying issue which is that all the database files get cleaned out from the git history regardless of which ones are updated. It does that so the git repository doesn't bubble up to a monstruous size over time, but it should not clean out databases that haven't been written back.

> can we expect GeoLite2-City.tar.gz to be always in the redist/ directory? (when the issue is fixed)

- you can
- however you cannot link to this file directly for [legal reasons](https://github.com/GitSquared/node-geolite2-redist#legal-warning), so please make sure you are using the redist npm package.
	- otherwise you're exposing yourself to takedown requests from MaxMind, and depending on your jurisdiction, possibly fines as well.
