### ISSUE TITLE
Checksum mismatch on latest commit

### ISSUE THREAD

**Issue by yunyu** [GitSquared/node-geolite2-redist#26]
This started happening as of 2 hours ago.
```
geolite2 self-update error: Error: Mismatched checksums for GeoLite2-Country
```

Two things:
* The old db folder is immediately deleted if there's a checksum error
* The latest released verison has a checksum error

Had to switch to `geolite2` to get prod back up

**Comment by GitSquared** [comment]
thanks for the report. I've pushed a force-update for the checksums and looking for a real patch to avoid this in the future.

**Comment by yunyu** [comment]
I think the best fix is to not delete the previous db files if an update fails so the download call can wrapped with try/catch?

**Comment by GitSquared** [comment]
@yunyu this is actually something the library does now. I was confused why it didn't work out but your [error message is an old one](https://github.com/GitSquared/node-geolite2-redist/blob/650e4c3dba5bdefc381ce61e5c5d69f414439d59/index.js#L90) from version 2 of this library.

You should update to the latest version `v3.0.2`. There's only a [slight breaking change](https://github.com/GitSquared/node-geolite2-redist/releases/tag/v3.0.0) and you'll get way more stability & even performance.
