### ISSUE TITLE
Failing in Yarn Pnp mode

### ISSUE THREAD

**Issue by agarwalvaibhav0211** [GitSquared/node-geolite2-redist#36]
We are trying to use this package in yarn pnp. Since the package by default stores the database in the package itself, and in Yarn , the package is packed into a ZipFS file, we are passing the db storage location.

But we are still facing the following error

```
Error: EROFS: read-only filesystem, rm '/node_modules/geolite2-redist/dbs-tmp'
```

I've traced down the error to https://github.com/GitSquared/node-geolite2-redist/blob/master/src/auto-updater.ts#L28. Why are we cleaning up the default path? Can we add a check here to not try to delete in case the default path is a read only path?

**Comment by GitSquared** [comment]
Thanks, that's an issue indeed! changed it to respect the custom directory option.

Released fix in https://github.com/GitSquared/node-geolite2-redist/releases/tag/v3.1.1
